# name: Build and Deploy to Docker Hub

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Check Out Repo
#       uses: actions/checkout@v2

#     - name: Log in to Docker Hub
#       uses: docker/login-action@v1
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}

#     - name: Build and Push Docker image
#       uses: docker/build-push-action@v2
#       with:
#         context: .
#         file: ./docker/Dockerfile.user
#         push: true
#         tags: kpiyush434/wallet1:latest  # Replace with your Docker Hub username and repository

#     - name: Verify Pushed Image
#       run: docker pull kpiyush434/wallet1:latest  # Replace with your Docker Hub username and repository

#     - name: Deploy to EC2
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.SSH_HOST }}
#         username: ${{ secrets.SSH_USERNAME }}
#         key: ${{ secrets.SSH_KEY }}
#         script: |
#           sudo docker pull kpiyush434/wallet1:latest
#           sudo docker stop web-app || true
#           sudo docker rm web-app || true
#           sudo docker run -e DATABASE_URL ${{SECRETS.DB_URL}} -d --name web-app -p 3005:3000 kpiyush434/wallet1:latest
name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile.user
        push: true
        tags: kpiyush434/wallet1:latest  # Replace with your Docker Hub username and repository

    - name: Verify Pushed Image
      run: docker pull kpiyush434/wallet1:latest  # Replace with your Docker Hub username and repository

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker pull kpiyush434/wallet1:latest
          sudo docker stop web-app || true
          sudo docker rm web-app || true
          sudo docker run --restart unless-stopped -e DATABASE_URL="${{ secrets.DB_URL }}" -d --name web-app -p 3005:3000 kpiyush434/wallet1:latest

    - name: Run Database Migrations
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker exec web-app npx prisma migrate deploy
